# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

notifications:
  email:
    on_success: false
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
